### PR TITLE
fix logic issue: handlers.removePeer() is called twice.

### PR DESCRIPTION
**Pull request by Jolly23**
### Description

There is a logic issue which causes "Ethereum peer removal failed, err=peer not registered" occur quite often.
Related issues #220 #670 #821

### Rationale

`handler.runEthPeer()` set up a `defer removePeer().` This is always called after a peer is disconnected.
However removePeer is also called by multiple functions like downloader/fetcher.  After those kind of functions call `removePeer()`, peer handler executes `defer removePeer()`. This makes `removePeer()` happened twice, and this is the reason we often see "Ethereum peer removal failed, err=peer not registered".

Just took a look, [go-ethereum code here](https://github.com/ethereum/go-ethereum/blob/59f0e8ae60c777bef384f045edf2a816c4a3ca9d/eth/handler.go#L484) is exactly using this new logic

### Changes

Notable changes: 
* `removePeer()` hard Disconnect peer from networking layer. 
* `defer unregisterPeer()` will called by  `handler.runEthPeer()`, do the cleanup task after then.
* add `NewPeerPipe()` under `p2p.Peer`, for RW close testing. The code is referenced from [go-ethereum-p2p-peer](https://github.com/ethereum/go-ethereum/blob/c40943a167b603382bbd0f45c92c9b9c2669a080/p2p/peer.go#L143)

### CODE REVIEW

**Comment by guagualvcha** [comment]
Thanks for the contribution. We will start review ASAP.

**Review by guagualvcha — APPROVED** [review]

**Comment by guagualvcha** [comment]
LGTM

**Comment by Jolly23** [comment]
Related issues #220 #670 #821

**Review by j75689 — APPROVED** [review]

**Review by Loverush — APPROVED** [review]

**Review by KeefeL — APPROVED** [review]
LGTM

**Pull request merged**
