### PR TITLE
eth/filters, ethclient/gethclient: add fullTx option to pending tx filter

### PR DESCRIPTION
**Pull request by lmittmann**
This PR is a cherry-pick of [go-ethereum#25186](https://github.com/ethereum/go-ethereum/pull/25186). It adds an option to subscribe to full pending transactions.

> This PR adds a way to subscribe to the _full_ pending transactions, as opposed to just being notified about hashes.
>
> In use cases where client subscribes to newPendingTransactions and gets txhashes only to then request the actual transaction, the caller can now shortcut that flow and obtain the transactions directly.

### CODE REVIEW

**Comment by lmittmann** [comment]
@brilliant-lx any chance of getting this upstream feature merged?

**Comment by brilliant-lx** [comment]
> @brilliant-lx any chance of getting this upstream feature merged?

@lmittmann sure, as it has been merged in ethereum, we are likely to include it as well. But we need double check. And could you rebase to the latest develop branch? thx

**Review by brilliant-lx — APPROVED** [review]

**Comment by buddh0** [comment]
func SubscribeFullPendingTransactions and NewPendingTransactions have been tested in unit test cases
func NewPendingTransactionFilter and GetFilterChanges have been tested in local env
image

**Review by buddh0 — APPROVED** [review]

**Comment by brilliant-lx** [comment]
merged, will be included in next release v1.2.8.
Thank you for you contribution.

**Comment by jwelch-qn** [comment]
Is there a way to toggle this setting? What if a user wanted to still get hashes as before?

**Comment by joseddg92** [comment]
Agreed, we need a way to toggle this, at least while it works like it does now. 'from' is missing and applications get broken.

**Pull request merged**
