### PR TITLE
go-duktape update & fix

### PR DESCRIPTION
**Pull request by freaker2k7**
### Description

Updated go-duktape from my fork of go-duktape and got rid of the annoying warning which is in the latest official repo:

```
duk_logging.c: In function ‘duk__logger_prototype_log_shared’:
duk_logging.c:184:64: warning: ‘Z’ directive writing 1 byte into a region of size between 0 and 9 [-Wformat-overflow=]
  184 |  sprintf((char *) date_buf, "%04d-%02d-%02dT%02d:%02d:%02d.%03dZ",
      |                                                                ^
In file included from /usr/include/stdio.h:867,
                 from duk_logging.c:5:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:36:10: note: ‘__builtin___sprintf_chk’ output between 25 and 85 bytes into a destination of size 32
   36 |   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   37 |       __bos (__s), __fmt, __va_arg_pack ());
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

See: https://github.com/freaker2k7/go-duktape/commit/41fcc4eaa087b83cb166a1c4df64e130e14da50e

Tested with 1.1.11 and it's working great.

### Rationale

Needed to update some libraries on my fork, so I though it'd be nice to contribute.
I archived my fork of go-duktape.

### Changes

Updated go-duktape from 2020's commit to 2022's (my commit) including the 2021's official commit of go-duktape.

### CODE REVIEW

**Comment by guagualvcha** [comment]
hi, @freaker2k7  Thanks for your contribution. Would you submit the PR to the `olebedev/go-duktape`?

**Comment by freaker2k7** [comment]
@guagualvcha I tried, but that repo is archived.
So I forked it, fixed, and archived as well, as a symbol of trust that this repo won't ever be altered.

**Comment by freaker2k7** [comment]
@guagualvcha Any updates ?

**Comment by brilliant-lx** [comment]
not sure if this PR still work, close right now since it is conflicted and not recommend to use private repo IMO.
Can reopen if it still bother you.

**Pull request closed without merging**
