### PR TITLE
chore: render system bytecode by go:embed

### PR DESCRIPTION
**Pull request by j75689**
### Description

render system bytecode by `go:embed`

no impact on the system.

### Rationale

As the system is upgraded, more and more `upgrade.go` files are expanding, making it difficult to open and review the code.

Use `go:embed` instead to render bytecode into the binary during compilation, which will reduce the difficulty of code maintenance in the future.

### Example

n/a

### Changes

Notable changes: 
* systemcontracrs

### CODE REVIEW

**Comment by zzzckck** [comment]
could include this PR after https://github.com/bnb-chain/bsc/pull/2200/

**Comment by j75689** [comment]
The code was generate by this tool -> https://github.com/j75689/bsc-bytecode-extraction-tool

**Review by setunapo — COMMENTED** [review]
Checked the bytecode of mainnet, it is ok.
Have setup a local env to run full sync for testnet/mainnet, will approve this PR once the local test passed, may take 2 weeks.

**Review by zzzckck — COMMENTED** [review]
the byte code of mainnet is ok.
Will run full sync for testnet/mainnet and approve this PR sync passed, could take 2 weeks.

**Review by buddh0 — APPROVED** [review]

**Comment by buddh0** [comment]
just ensure that hash of all codes not change after this PR
run the UT on develop branch and this PR based branch, both will pass

**Review by zzzckck — APPROVED** [review]

**Review by zzzckck — CHANGES_REQUESTED** [review]
Wait

**Review by zzzckck — APPROVED** [review]

**Pull request merged**
