### PR TITLE
fix: trieJournal format compatible old db format

### PR DESCRIPTION
**Pull request by jingjunLi**
### Description

If trieJournal is stored in the database, it retains the old journal format; if trieJournal writes to the journal file using the new journal format;

### Rationale

tell us why we need these changes...

### Example

add an example CLI or API response...

### Changes

Notable changes: 
* add each change in a bullet point here
* ...

### CODE REVIEW

**Review by RenRick — DISMISSED** [review]
LGTM

**Review by Fynnss — DISMISSED** [review]
LGTM

**Comment by NathanBSC** [comment]
can we avoid to change the interface of function loadDiffLayer, loadDiskLayer and journal?
we can already get JournalFilePath by `db.config.JournalFilePath`

**Comment by NathanBSC** [comment]
why a field `length` is need?
rlp decode will not use it, I also can't see other usage

**Review by NathanBSC — APPROVED** [review]

**Review by buddh0 — APPROVED** [review]

**Review by zzzckck — APPROVED** [review]

**Pull request merged**
